spring:
    profiles:
        active: test
    jpa:
        open-in-view: false
security:
    oauth2:
        client:
            client-id: reviews
            client-secret: reviews123
jwt:
    secret: MY-JWT-SECRET
    duration: 86400